/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   JNIFunc.h
 * Author: root
 *
 * Created on September 28, 2017, 8:10 PM
 */

#ifndef JNIFUNC_H
#define JNIFUNC_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "./../lib-dwg-master/dwg.h"


#ifdef __cplusplus
extern "C" {
#endif

    typedef struct tagApp {
        bool IsBusy;
        JNIEnv *JNIenv;
        jobject JNIjobj;

        Dwg_Data DwgData;
        int DwgID = 0;

    } APP, *LP_APP;


    JNIEXPORT APP App = {0};

    JNIEXPORT jstring JNICALL Java_xprojectcam_main_Main_nGetVersion(JNIEnv *jenv, jobject jobj);
    JNIEXPORT jint JNICALL Java_xprojectcam_main_Main_nDrawScene(JNIEnv *jenv, jobject jobj, jint mode);

#ifdef __cplusplus
}
#endif

#endif /* JNIFUNC_H */

